FROM php:8.2-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    libicu-dev \
    libonig-dev \
    && docker-php-ext-install \
    pdo_mysql \
    zip \
    intl \
    mbstring \
    opcache

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www/symfony

# Copy project files - REMOVED for Dev (Volume Mount used instead)
# COPY . .

# Install PHP dependencies - REMOVED for Dev
# RUN composer install ...

CMD ["php-fpm"]
