<?php

declare(strict_types=1);

namespace App\Contremarque\Repository\ORM\Doctrine;

use App\Common\Repository\ORM\Doctrine\DoctrineORMRepository;
use App\Contremarque\Entity\ImageAttachment;
use App\Contremarque\Entity\Image;
use App\Contremarque\Repository\ImageAttachmentRepository;
use App\Contremarque\Repository\ImageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

class DoctrineORMImageAttachmentRepository extends DoctrineORMRepository implements ImageAttachmentRepository
{
    protected const ENTITY_CLASS = ImageAttachment::class;
    protected const ALIAS = 'imageAttachment';
    private readonly ParameterBagInterface $params;

    public function __construct(
        EntityManagerInterface           $manager,
        private readonly ImageRepository $imageRepository
    )
    {
        parent::__construct($manager, self::ENTITY_CLASS, self::ALIAS);
    }

    public function deleteByAttachment($image): void
    {
        $this->manager->createQueryBuilder()
            ->delete(self::ENTITY_CLASS, self::ALIAS)
            ->where(self::ALIAS . '.attachment = :attachment')
            ->setParameter('attachment', $image)
            ->getQuery()
            ->execute();
    }

    public function removeByImage(Image $image): void
    {
        $attachment = $this->findOneBy(['image' => $image]);

        if (null === $attachment) {
            return;
        }

        $this->remove($attachment);
    }

    /**
     * @return void
     */
    public function create(array $data)
    {
        // TODO: Implement create() method.
    }

    /**
     * @return void
     */
    public function update($entity, array $data)
    {
        // TODO: Implement update() method.
    }

    /**
     * @return void
     */
    public function remove(object $entity)
    {
        $file = $entity->getAttachment()->getFile();
        $path = $entity->getAttachment()->getPath();
        $filePath = $path . '/' . $file;
        if (file_exists($filePath)) {
            unlink($filePath);
        }
        parent::remove($entity); // TODO: Change the autogenerated stub
    }

    /**
     * @return null|object
     */
    public function findVignette($order, $location = false)
    {
        $where = '';
        if ($location) {
            $where = ' AND cdo.location_id=' . $location->getId();
        }
        $sql = "SELECT i.id FROM image i
                LEFT JOIN image_type it ON(it.id=i.image_type_id)
                LEFT JOIN carpet_design_order cdo ON(cdo.id=i.carpet_design_order_id)
                WHERE i.carpet_design_order_id= :orderDesignOrderId
                AND it.name='Vignette'
                " . $where . '
                ORDER BY i.id DESC
                ';

        // Prepare and execute the statement with a bound parameter
        $stmt = $this->manager->getConnection()->prepare($sql);
        $stmt->bindValue(':orderDesignOrderId', (int)$order->getId());

        // Fetch the results
        $result = $stmt->execute()->fetchOne();

        // Check if any IDs are found
        if (empty($result)) {
            return null;
        }

        $image = $this->imageRepository->find((int)$result);

        // Find the entities using the extracted IDs
        return $this->findOneBy(['image' => $image]);
    }

    /**
     * @return null|object
     */
    public function findByType($order, string $type, $location = null)
    {
        $where = '';
        if ($location) {
            $where = ' AND cdo.location_id = :locationId';
        }

        $sql = "SELECT i.id FROM image i
            LEFT JOIN image_type it ON it.id = i.image_type_id
            LEFT JOIN carpet_design_order cdo ON cdo.id = i.carpet_design_order_id
            WHERE i.carpet_design_order_id = :orderDesignOrderId
            AND it.name = :type
            $where
            ORDER BY i.id DESC";

        // Prepare and execute the statement with bound parameters
        $stmt = $this->manager->getConnection()->prepare($sql);
        $stmt->bindValue(':orderDesignOrderId', (int)$order->getId());
        $stmt->bindValue(':type', $type);

        if ($location) {
            $stmt->bindValue(':locationId', (int)$location->getId());
        }

        // Fetch the first result
        $result = $stmt->executeQuery()->fetchOne();

        if (!$result) {
            return null;
        }

        // Fetch the image entity by ID
        $image = $this->imageRepository->find((int)$result);

        if (!$image) {
            return null;
        }

        return $this->findOneBy(['image' => $image]);
    }
}
